select = [
  "AIR",     # Airflow
  "ASYNC",   # flake8-async
  "BLE",     # flake8-blind-except
  "C4",      # flake8-comprehensions
  "C901",    # McCabe cyclomatic complexity
  "CPY",     # Copyright-related rules
  "DTZ",     # flake8-datetimez
  "E",       # pycodestyle
  "F",       # Pyflakes
  "FLY",     # flynt
  "I",       # isort
  "ICN",     # flake8-import-conventions
  "INT",     # flake8-gettext
  "NPY",     # NumPy-specific rules
  "PL",      # Pylint
  "PYI",     # flake8-pyi
  "RSE",     # flake8-raise
  "RUF",     # Ruff-specific rules
  "S",       # flake8-bandit
  "SLOT",    # flake8-slots
  "T10",     # flake8-debugger
  "TID",     # flake8-tidy-imports
  "UP",      # pyupgrade
  "W",       # pycodestyle
  "YTT",     # flake8-2020
  # TODO: add when we push for the docs
  # "D",   # pydocstyle
]

line-length = 120
target-version = "py38"

[mccabe]
max-complexity = 39

[pylint]
max-args = 16
max-branches = 45
max-returns = 13
max-statements = 258

[per-file-ignores]
"py/tests/*" = [
  "S101",     # Use of `assert` detected
  "PLR2004",  # Magic value used in comparison,
  "RUF006",   # Store a reference to the return value of `asyncio.create_task
]
