var dir_f2976b1aed94f4f9facd865c460fbab2 =
[
    [ "impl", "dir_492e73dedf73de889b7df5db0b5789fe.html", "dir_492e73dedf73de889b7df5db0b5789fe" ],
    [ "interp", "dir_a7702305d6d70440fe3dca2b90ee7c7d.html", "dir_a7702305d6d70440fe3dca2b90ee7c7d" ],
    [ "group_manifold.h", "group__manifold_8h.html", "group__manifold_8h" ],
    [ "group_manifold_test.cpp", "group__manifold__test_8cpp.html", "group__manifold__test_8cpp" ],
    [ "identity.h", "identity_8h.html", "identity_8h" ],
    [ "identity_test.cpp", "identity__test_8cpp.html", "identity__test_8cpp" ],
    [ "isometry2.h", "isometry2_8h.html", "isometry2_8h" ],
    [ "isometry2_test.cpp", "isometry2__test_8cpp.html", "isometry2__test_8cpp" ],
    [ "isometry3.h", "isometry3_8h.html", "isometry3_8h" ],
    [ "isometry3_test.cpp", "isometry3__test_8cpp.html", "isometry3__test_8cpp" ],
    [ "lie_group.h", "lie_2lie__group_8h.html", [
      [ "Group", "classsophus_1_1lie_1_1_group.html", "classsophus_1_1lie_1_1_group" ]
    ] ],
    [ "lie_group_test.cpp", "lie_2lie__group__test_8cpp.html", "lie_2lie__group__test_8cpp" ],
    [ "pose3.h", "pose3_8h.html", "pose3_8h" ],
    [ "pose3_test.cpp", "pose3__test_8cpp.html", "pose3__test_8cpp" ],
    [ "rotation2.h", "rotation2_8h.html", "rotation2_8h" ],
    [ "rotation2_test.cpp", "rotation2__test_8cpp.html", "rotation2__test_8cpp" ],
    [ "rotation3.h", "rotation3_8h.html", "rotation3_8h" ],
    [ "rotation3_test.cpp", "rotation3__test_8cpp.html", "rotation3__test_8cpp" ],
    [ "scaling.h", "scaling_8h.html", "scaling_8h" ],
    [ "scaling_test.cpp", "scaling__test_8cpp.html", "scaling__test_8cpp" ],
    [ "scaling_translation.h", "scaling__translation_8h.html", "scaling__translation_8h" ],
    [ "scaling_translation_test.cpp", "scaling__translation__test_8cpp.html", "scaling__translation__test_8cpp" ],
    [ "se3.h", "se3_8h.html", null ],
    [ "similarity2.h", "similarity2_8h.html", "similarity2_8h" ],
    [ "similarity2_test.cpp", "similarity2__test_8cpp.html", "similarity2__test_8cpp" ],
    [ "similarity3.h", "similarity3_8h.html", "similarity3_8h" ],
    [ "similarity3_test.cpp", "similarity3__test_8cpp.html", "similarity3__test_8cpp" ],
    [ "so3.h", "so3_8h.html", null ],
    [ "spiral_similarity2.h", "spiral__similarity2_8h.html", "spiral__similarity2_8h" ],
    [ "spiral_similarity2_test.cpp", "spiral__similarity2__test_8cpp.html", "spiral__similarity2__test_8cpp" ],
    [ "spiral_similarity3.h", "spiral__similarity3_8h.html", "spiral__similarity3_8h" ],
    [ "spiral_similarity3_test.cpp", "spiral__similarity3__test_8cpp.html", "spiral__similarity3__test_8cpp" ],
    [ "translation.h", "translation_8h.html", "translation_8h" ],
    [ "translation_test.cpp", "translation__test_8cpp.html", "translation__test_8cpp" ]
];