var namespacefarm__ng =
[
    [ "details", "namespacefarm__ng_1_1details.html", "namespacefarm__ng_1_1details" ],
    [ "plotting", "namespacefarm__ng_1_1plotting.html", "namespacefarm__ng_1_1plotting" ],
    [ "proto_conv_details", "namespacefarm__ng_1_1proto__conv__details.html", "namespacefarm__ng_1_1proto__conv__details" ],
    [ "testing", "namespacefarm__ng_1_1testing.html", "namespacefarm__ng_1_1testing" ],
    [ "time_series", "namespacefarm__ng_1_1time__series.html", "namespacefarm__ng_1_1time__series" ],
    [ "A", "structfarm__ng_1_1_a.html", "structfarm__ng_1_1_a" ],
    [ "Ab", "structfarm__ng_1_1_ab.html", "structfarm__ng_1_1_ab" ],
    [ "Abc", "structfarm__ng_1_1_abc.html", "structfarm__ng_1_1_abc" ],
    [ "Adder", "classfarm__ng_1_1_adder.html", "classfarm__ng_1_1_adder" ],
    [ "Component", "classfarm__ng_1_1_component.html", "classfarm__ng_1_1_component" ],
    [ "Context", "classfarm__ng_1_1_context.html", "classfarm__ng_1_1_context" ],
    [ "ContextStrand", "classfarm__ng_1_1_context_strand.html", "classfarm__ng_1_1_context_strand" ],
    [ "Error", "structfarm__ng_1_1_error.html", "structfarm__ng_1_1_error" ],
    [ "ErrorDetail", "structfarm__ng_1_1_error_detail.html", "structfarm__ng_1_1_error_detail" ],
    [ "EventLogEof", "classfarm__ng_1_1_event_log_eof.html", "classfarm__ng_1_1_event_log_eof" ],
    [ "EventLogExist", "classfarm__ng_1_1_event_log_exist.html", "classfarm__ng_1_1_event_log_exist" ],
    [ "EventLogPos", "classfarm__ng_1_1_event_log_pos.html", "classfarm__ng_1_1_event_log_pos" ],
    [ "EventLogReader", "classfarm__ng_1_1_event_log_reader.html", "classfarm__ng_1_1_event_log_reader" ],
    [ "EventLogReaderBase", "structfarm__ng_1_1_event_log_reader_base.html", "structfarm__ng_1_1_event_log_reader_base" ],
    [ "EventLogWriter", "classfarm__ng_1_1_event_log_writer.html", "classfarm__ng_1_1_event_log_writer" ],
    [ "EventTimeCompareClockAndSemantics", "structfarm__ng_1_1_event_time_compare_clock_and_semantics.html", "structfarm__ng_1_1_event_time_compare_clock_and_semantics" ],
    [ "FromProtImpl", "structfarm__ng_1_1_from_prot_impl.html", null ],
    [ "FromProtoTrait", "structfarm__ng_1_1_from_proto_trait.html", null ],
    [ "HasType", "structfarm__ng_1_1_has_type.html", null ],
    [ "HasType< T, std::variant< Us... > >", "structfarm__ng_1_1_has_type_3_01_t_00_01std_1_1variant_3_01_us_8_8_8_01_4_01_4.html", null ],
    [ "Input", "classfarm__ng_1_1_input.html", "classfarm__ng_1_1_input" ],
    [ "InputConfig", "classfarm__ng_1_1_input_config.html", "classfarm__ng_1_1_input_config" ],
    [ "Output", "classfarm__ng_1_1_output.html", "classfarm__ng_1_1_output" ],
    [ "Overload", "structfarm__ng_1_1_overload.html", null ],
    [ "PlottingComponent", "classfarm__ng_1_1_plotting_component.html", "classfarm__ng_1_1_plotting_component" ],
    [ "PlottingComponentImpl", "structfarm__ng_1_1_plotting_component_impl.html", "structfarm__ng_1_1_plotting_component_impl" ],
    [ "PlottingRemoteClientImpl", "classfarm__ng_1_1_plotting_remote_client_impl.html", "classfarm__ng_1_1_plotting_remote_client_impl" ],
    [ "Printer", "classfarm__ng_1_1_printer.html", "classfarm__ng_1_1_printer" ],
    [ "RemotePlottingClient", "classfarm__ng_1_1_remote_plotting_client.html", "classfarm__ng_1_1_remote_plotting_client" ],
    [ "ScopedTimer", "structfarm__ng_1_1_scoped_timer.html", "structfarm__ng_1_1_scoped_timer" ],
    [ "Shared", "classfarm__ng_1_1_shared.html", "classfarm__ng_1_1_shared" ],
    [ "StampedBar", "structfarm__ng_1_1_stamped_bar.html", "structfarm__ng_1_1_stamped_bar" ],
    [ "StampedFoo", "structfarm__ng_1_1_stamped_foo.html", "structfarm__ng_1_1_stamped_foo" ],
    [ "StampedInterpolative", "structfarm__ng_1_1_stamped_interpolative.html", "structfarm__ng_1_1_stamped_interpolative" ],
    [ "StopwatchSingleton", "classfarm__ng_1_1_stopwatch_singleton.html", "classfarm__ng_1_1_stopwatch_singleton" ],
    [ "StreamLogger", "classfarm__ng_1_1_stream_logger.html", "classfarm__ng_1_1_stream_logger" ],
    [ "Success", "structfarm__ng_1_1_success.html", null ],
    [ "ThreadPool", "classfarm__ng_1_1_thread_pool.html", "classfarm__ng_1_1_thread_pool" ],
    [ "TimeSeries", "classfarm__ng_1_1_time_series.html", "classfarm__ng_1_1_time_series" ],
    [ "ToProtImpl", "structfarm__ng_1_1_to_prot_impl.html", null ],
    [ "ToProtoTrait", "structfarm__ng_1_1_to_proto_trait.html", null ],
    [ "ToProtoTrait< sophus::IntensityImage<> >", "structfarm__ng_1_1_to_proto_trait_3_01sophus_1_1_intensity_image_3_4_01_4.html", "structfarm__ng_1_1_to_proto_trait_3_01sophus_1_1_intensity_image_3_4_01_4" ],
    [ "Uri", "structfarm__ng_1_1_uri.html", "structfarm__ng_1_1_uri" ],
    [ "Void", "structfarm__ng_1_1_void.html", null ]
];