on:
  push:
    branches: [ main, sophus2 ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false


    steps:
      - uses: actions/checkout@v2

      - name: Run sympy tests
        run: |
          pip3 install sympy==1.8
          cd py/sympy
          ./run_tests.sh
