ExternalProject_Add(Sophus
    DEPENDS farm-ng-core eigen ceres
    PREFIX ${farm_ng_EXT_PREFIX}
    SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Sophus
    BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/Sophus-build
    CMAKE_ARGS ${farm_ng_DEFAULT_ARGS}
    -DBUILD_FARM_NG_PROTOS=On
    -DBUILD_SOPHUS_TESTS=ON
    TEST_BEFORE_INSTALL ON
)
