set(farm_ng_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/prefix")
set(farm_ng_EXT_PREFIX "${CMAKE_BINARY_DIR}/ext")

set(farm_ng_DEFAULT_ARGS
  "-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}"
  "-DCMAKE_PREFIX_PATH:PATH=${farm_ng_INSTALL_PREFIX};${CMAKE_PREFIX_PATH}"
  "-DCMAKE_INSTALL_PREFIX:PATH=${farm_ng_INSTALL_PREFIX}")
include(ExternalProject)