find_program(CCACHE_FOUND ccache)
if(CCACHE_FOUND)
  message("Enabling ccache")
  set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
  set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
else()
  message("Ccache not found.")
endif(CCACHE_FOUND)
