name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            compiler: gcc
          - os: ubuntu-20.04
            compiler: clang
          - os: macos-12
            compiler: clang
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
    - name: Install dependencies (Ubuntu)
      working-directory: ./infra/scripts
      run: |
        ./install_deps_ubuntu.sh
      if: matrix.os == 'ubuntu-20.04'

    - name: Install dependencies (Mac)
      working-directory: ./infra/scripts
      run: |
        ./install_deps_mac.sh
      if: matrix.os == 'macos-12'

    - name: Download dependencies (proto)
      working-directory: ./infra/
      run: |
        source ./bootstrap_venv.sh
        cd scripts
        ./install_farm_ng_cmake.sh

    - name: Compile (gcc)
      working-directory: ./infra/scripts
      run: |
          ls
          source ../venv/bin/activate
          ./compile_gcc.sh
      if: matrix.compiler == 'gcc'

    - name: Compile (clang)
      working-directory: ./infra/scripts
      run: |
        ls
        source ../venv/bin/activate
        ./compile_clang.sh
      if: matrix.compiler == 'clang'

    - name: clang-tidy
      working-directory: ./infra/
      run: |
        source ./bootstrap_venv.sh
        cd ..
        ./run_clang_tidy.sh
      if: matrix.os == 'ubuntu-20.04' && matrix.compiler == 'clang'
