name: format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit-check:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout workspace
          uses: actions/checkout@v3
        - name: ccache
          uses: hendrikmuhs/ccache-action@v1
        - name: Run pre-commit checks
          run: pre-commit run --all-files
